server:
  port: 8091
  servlet:
    context-path: /springbootlogin
name:
  firstname: jie
  lastname: Mark
  fullname: ${name.firstname} ${name.lastname}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: Rout997279
mybatis:
  type-aliases-package: com.jie.springbootlogin
  mapper-locations: classpath:/mapper/*.xml